### ISSUE TITLE
Sign Up link in readme is broken

### ISSUE THREAD

**Issue by ttlew** [watson-developer-cloud/conversation-simple#108]
The first link is broken in the readme. It should be directed to: https://console.ng.bluemix.net/registration/?target=/catalog/%3fcategory=watson

**Comment by ttlew** [comment]
@stevenpkg would you be able to fix this

**Comment by stevenpkg** [comment]
Yes I can do this, which app is it you wish me to update?

**Comment by stevenpkg** [comment]
sorry, to much on my mind, will update link in conversation-simple

**Comment by stevenpkg** [comment]
Just need to check a couple of things. If I follow your link

https://console.ng.bluemix.net/registration/?target=/catalog/%3fcategory=watson

 I cannot see

2. From the All Items tab, click the newly created Conversation service in the Services list.

Should the link be this, where the new conversation service is?

https://console.ng.bluemix.net/dashboard/services

**Comment by ttlew** [comment]
No this initial link I believe is to direct straight to the Bluemix registration page for new users. We provide the second link later in the readme to direct users to the Conversation service.
