### ISSUE TITLE
This failure might be due to the use of legacy binary "node"

### ISSUE THREAD

**Issue by iraj4t** [watson-developer-cloud/conversation-simple#109]
Use of legacy term node in the server.js file.I have attached a screenshot of my workspace.
![issue](https://cloud.githubusercontent.com/assets/12109933/25041608/cbb0cf8a-212e-11e7-82c9-39272892d673.JPG)

**Comment by germanattanasio** [comment]
This is because you are using node < 4.0 and we are using es6.
Update your node version

**Comment by iraj4t** [comment]
Is there any possibility for support of node < 4.0. If possible.
I have tried using node-legacy package in order to solve the issue but got frequent errors.

**Comment by germanattanasio** [comment]
Node.js 4 let us write ES6 and enable as few features that we think are important. We could use babel but the decision was to use a newer version of Node.

Node 0.10 is not even supported in Bluemix so this won't make sense for the purpose of this sample
