### ISSUE TITLE
npm start fails 

### ISSUE THREAD

**Issue by mohanish12** [watson-developer-cloud/conversation-simple#115]
hi,

Application start fails with npm start with below error log.

> conversation-simple@0.1.1 start c:\test
> node server.js

c:\test\node_modules\watson-developer-cloud\lib\base_service.js:73
      throw new Error('Argument error: username and password are required unless
 use_unauthenticated is set');
      ^

Error: Argument error: username and password are required unless use_unauthentic
ated is set
    at ConversationV1.BaseService.initCredentials (c:\test\node_modules\watson-d
eveloper-cloud\lib\base_service.js:73:13)
    at ConversationV1.BaseService (c:\test\node_modules\watson-developer-cloud\l
ib\base_service.js:44:18)
    at new ConversationV1 (c:\test\node_modules\watson-developer-cloud\conversat
ion\v1.js:31:15)
    at Object.<anonymous> (c:\test\app.js:30:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! conversation-simple@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the conversation-simple@0.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the conversation-simple p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs conversation-simple
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls conversation-simple
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\test\npm-debug.log

npm-debug.log is as below

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle conversation-simple@0.1.1~prestart: conversation-simple@0.1.1
6 silly lifecycle conversation-simple@0.1.1~prestart: no script for prestart, continuing
7 info lifecycle conversation-simple@0.1.1~start: conversation-simple@0.1.1
8 verbose lifecycle conversation-simple@0.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle conversation-simple@0.1.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\test\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Cloud Foundry;C:\Users\Mohanish\AppData\Roaming\npm
10 verbose lifecycle conversation-simple@0.1.1~start: CWD: c:\test
11 silly lifecycle conversation-simple@0.1.1~start: Args: [ '/d /s /c', 'node server.js' ]
12 silly lifecycle conversation-simple@0.1.1~start: Returned: code: 1  signal: null
13 info lifecycle conversation-simple@0.1.1~start: Failed to exec start script
14 verbose stack Error: conversation-simple@0.1.1 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid conversation-simple@0.1.1
16 verbose cwd c:\test
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error conversation-simple@0.1.1 start: `node server.js`
22 error Exit status 1
23 error Failed at the conversation-simple@0.1.1 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the conversation-simple package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs conversation-simple
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls conversation-simple
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ttlew** [comment]
thanks for submitting an issue. we'll look into it @stevenpkg

**Comment by stevenpkg** [comment]
Not sure what the problem is, can you run "npm test"

**Comment by germanattanasio** [comment]
@mohanish12 make sure you follow the steps in the readme.md I think you are not specifying the username and password in the `.env` file

**Comment by virtrap** [comment]
I've similar issue above. Went thru' readme.md few times and ensure myKey.env have the right credentials. No luck.

**Comment by virtrap** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\myapps\\nodejs\\node.exe',
1 verbose cli   'C:\\myapps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle conversation-simple@0.1.1~prestart: conversation-simple@0.1.1
6 silly lifecycle conversation-simple@0.1.1~prestart: no script for prestart, continuing
7 info lifecycle conversation-simple@0.1.1~start: conversation-simple@0.1.1
8 verbose lifecycle conversation-simple@0.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle conversation-simple@0.1.1~start: PATH: C:\myapps\nodejs\node_modules\npm\bin\node-gyp-bin;C:\workspace\conversation-simple\node_modules\.bin;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Oracle\product\11.2.0.3\32bit_client\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Lotus\Notes;C:\Program Files (x86)\Serena\Dimensions 12.2\CM\prog64\;C:\PROGRA~1\BMCSOF~1\common\globalc\bin\Windows-x86;C:\PROGRA~1\BMCSOF~1\common\globalc\bin\Windows-x86-64;C:\PROGRA~1\BMCSOF~1\common\bmc\bin\Windows-x86;C:\PROGRA~1\BMCSOF~1\common\bmc\bin\Windows-x86-64;C:\PROGRA~1\BMCSOF~1\Patrol3\bin;C:\PROGRA~1\BMCSOF~1\Patrol7\bin\Windows-x86;C:\Program Files (x86)\Serena\Dimensions 14.3\CM\prog64;C:\Program Files (x86)\Serena\Dimensions 14.3\CM\prog;C:\Program Files (x86)\Serena\Dimensions 14.3\CM\prog64\;C:\Program Files (x86)\Personal Communications\;C:\Program Files (x86)\IBM\Trace Facility\;C:\apache-maven-3.3.9\bin;C:\Program Files\Git\cmd;C:\myapps\nodejs\;C:\myapps\CloudFoundry;C:\Users\ct98\AppData\Roaming\npm
10 verbose lifecycle conversation-simple@0.1.1~start: CWD: C:\workspace\conversation-simple
11 silly lifecycle conversation-simple@0.1.1~start: Args: [ '/d /s /c', 'node server.js' ]
12 silly lifecycle conversation-simple@0.1.1~start: Returned: code: 1  signal: null
13 info lifecycle conversation-simple@0.1.1~start: Failed to exec start script
14 verbose stack Error: conversation-simple@0.1.1 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\myapps\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\myapps\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid conversation-simple@0.1.1
16 verbose cwd C:\workspace\conversation-simple
17 error Windows_NT 6.1.7601
18 error argv "C:\\myapps\\nodejs\\node.exe" "C:\\myapps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error conversation-simple@0.1.1 start: `node server.js`
22 error Exit status 1
23 error Failed at the conversation-simple@0.1.1 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the conversation-simple package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs conversation-simple
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls conversation-simple
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by stevenpkg** [comment]
I just tried this from scratch, and everything was okay?

Let me just make sure you are following these steps:

1) clone or download the conversation-simple into a local folder

Then from within your folder containing conversation-simple repository
2) copy or rename "example.env" to ".env" (this is now a hidden file)
3) fill out
WORKSPACE_ID=<workspace-id>
CONVERSATION_USERNAME=<conversation-username>
CONVERSATION_PASSWORD=<conversation-password>
4) npm install
5) npm start

let me know if you are doing these steps

**Comment by virtrap** [comment]
My env file was not named'.env' .. After renaming like above, it works now. Thanks for your quick support.

**Comment by mohanish12** [comment]
hi,

I did not get the part about the .env file.
The package contains .env.example file. I populated the fields in it and
renamed it test.env.
If I just leave it as .env its not accepting as it says it needs a filename.

Please if you can help.


Thanks and Regards
Mohanish Mahajan

**Comment by mohanish12** [comment]
hi Steve,

Yes I did this but this also didnt worked.


Thanks and Regards
Mohanish Mahajan

**Comment by stevenpkg** [comment]
You must rename .example.env to .env

Perhaps the best way is on the command line

rename .example.env .env

**Comment by mohanish12** [comment]
hi Steve,

I tried as per your suggestion below however still got the same error. PFB
the error log:-
I have checked the .env file contents and they  contain the Workspace ID,
Username, Password of by Bluemix service conversation.
Let me know if we can have a remote session so that you can have a look
into it.

c:\test>npm start

> conversation-simple@0.1.1 start c:\test
> node server.js

c:\test\node_modules\watson-developer-cloud\lib\base_service.js:73
      throw new Error('Argument error: username and password are required
unless
 use_unauthenticated is set');
      ^

Error: Argument error: username and password are required unless
use_unauthentic
ated is set
    at ConversationV1.BaseService.initCredentials
(c:\test\node_modules\watson-d
eveloper-cloud\lib\base_service.js:73:13)
    at ConversationV1.BaseService
(c:\test\node_modules\watson-developer-cloud\l
ib\base_service.js:44:18)
    at new ConversationV1
(c:\test\node_modules\watson-developer-cloud\conversat
ion\v1.js:31:15)
    at Object.<anonymous> (c:\test\app.js:30:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! conversation-simple@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the conversation-simple@0.1.1 start script 'node
server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the
conversation-simple p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs conversation-simple
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls conversation-simple
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\test\npm-debug.log

c:\test>


Thanks and Regards
Mohanish Mahajan

I

**Comment by germanattanasio** [comment]
@mohanish12 As you can see in the error log you are missing the credentials for conversation.

You need to have a `.env` and it should contain the credentials for conversation otherwise, the app won't start.

As @stevenpkg said, there is nothing wrong on our side as your error is because you didn't specify the credentials.

**Comment by mohanish12** [comment]
Hi

I have a .env file and I have entered the credentials in there. But still
its not starting.
Below are the contents of my .env file. I am mentioning WorkspaceID,
Username and password as defined in help and .md file.
Please if you can help to know if I am missing anything. Actual content
ommited to preserve password

# Environment variables
WORKSPACE_ID=49fa48dexxxxxxxxxxx
CONVERSATION_USERNAME=a8f2xxxxxxxxxxxxxxxx
CONVERSATION_PASSWORD=6Mxxxxxxxxxxxxx



Thanks and REgards
Mohanish Mahajan

**Comment by stevenpkg** [comment]
If you are in windows, can you give me the result of running "dir" in the project folder containing the ".env" file in Mac or Linux run "ls -la"

**Comment by mohanish12** [comment]
hi Steve,

PFB the required output. Please if you can help resolve:-

c:\test>dir
 Volume in drive C has no label.
 Volume Serial Number is D8ED-F27B

 Directory of c:\test

05/01/2017  07:30 AM    <DIR>          .
05/01/2017  07:30 AM    <DIR>          ..
04/18/2017  02:32 PM                63 .cfignore
04/29/2017  12:55 PM               157 .env
04/18/2017  02:32 PM                 8 .eslintignore
04/18/2017  02:32 PM               225 .eslintrc.yml
04/18/2017  02:32 PM                11 .gitattributes
04/18/2017  02:32 PM                60 .gitignore
04/18/2017  02:32 PM               471 .travis.yml
04/18/2017  02:32 PM             3,930 app.js
04/18/2017  02:32 PM             1,535 casper-runner.js
04/18/2017  02:32 PM               766 CONTRIBUTING.md
04/29/2017  12:56 PM    <DIR>          coverage
04/18/2017  02:32 PM            10,173 LICENSE
04/18/2017  02:32 PM               272 manifest.yml
05/01/2017  07:30 AM    <DIR>          node_modules
05/01/2017  07:30 AM             3,119 npm-debug.log
04/18/2017  02:32 PM             1,266 package.json
04/18/2017  02:32 PM                14 Procfile
04/23/2017  12:39 PM    <DIR>          public
04/18/2017  02:32 PM             8,304 README.md
04/23/2017  12:39 PM    <DIR>          readme_images
04/18/2017  02:32 PM               906 server.js
04/23/2017  12:40 PM    <DIR>          test
04/23/2017  12:40 PM    <DIR>          training
              17 File(s)         31,280 bytes
               8 Dir(s)  123,703,504,896 bytes free

c:\test>


Thanks and Regards
Mohanish Mahajan

**Comment by stevenpkg** [comment]
Not sure I see you have a ".env" file. Can you email your ".env" file so I can test. Send to stevenpkg@au1.ibm.com

**Comment by Rou9aya** [comment]
Did you solve the problem! I have the same one

**Comment by stevenpkg** [comment]
Was not sure what the problem was? If you have a simular problem, please send me the console errors so I can have a look

**Comment by Rou9aya** [comment]
thnx it worked
