### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by mohanish12** [watson-developer-cloud/conversation-simple#117]
Hi,

as per my issue reported earlier under issue#115 
I had reported that npm start fails out.
The suggestions on that asked to change and rename .env file and to verify credentials.
I renamed the .env.example file to test.env and all values for Workplace ID, Conversation USername and conversation password are filled correctly. Blow is the error I am getting. Please if you can help

c:\test>npm start

> conversation-simple@0.1.1 start c:\test
> node server.js

c:\test\node_modules\watson-developer-cloud\lib\base_service.js:73
      throw new Error('Argument error: username and password are required unless
 use_unauthenticated is set');
      ^

Error: Argument error: username and password are required unless use_unauthentic
ated is set
    at ConversationV1.BaseService.initCredentials (c:\test\node_modules\watson-d
eveloper-cloud\lib\base_service.js:73:13)
    at ConversationV1.BaseService (c:\test\node_modules\watson-developer-cloud\l
ib\base_service.js:44:18)
    at new ConversationV1 (c:\test\node_modules\watson-developer-cloud\conversat
ion\v1.js:31:15)
    at Object.<anonymous> (c:\test\app.js:30:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! conversation-simple@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the conversation-simple@0.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the conversation-simple p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs conversation-simple
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls conversation-simple
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\test\npm-debug.log

**Comment by harshalwavre7** [comment]
Facing the Above mentioned Issue

**Comment by Oliver-I** [comment]
@stevenpkg would you be able to help here?

**Comment by stevenpkg** [comment]
The ".example.env" MUST be renamed to ".env" (nothing before the dot) and have the correct credentials for the conversation service

**Comment by germanattanasio** [comment]
This is working for me. Make sure the `.env` file has all the required arguments
