### ISSUE TITLE
npm start does nothing

### ISSUE THREAD

**Issue by 1234hansel** [watson-developer-cloud/conversation-simple#118]
hi, 
so I did everything as described and it's not working out. npm install seems to work fine. npm start shows me this: 
<img width="567" alt="screen shot 2017-05-05 at 21 32 27" src="https://cloud.githubusercontent.com/assets/28457298/25761227/70c087ac-31da-11e7-9f4e-87e2ba08d72d.png">

and it just stops there. and my app is therefor empty (local and on bluemix of course) 

can you help me?

**Comment by mitchmason** [comment]
what happens when you navigate to localhost:3000 ?

**Comment by 1234hansel** [comment]
you mean in my browser? 
shows me this:
<img width="1433" alt="screen shot 2017-05-05 at 21 38 03" src="https://cloud.githubusercontent.com/assets/28457298/25761488/3e736890-31db-11e7-89b0-c3dae1944951.png">

sweet nothings :/

**Comment by mitchmason** [comment]
right, but that means the app is running, did you also configure the .env file correctly? dont paste it here obviously. also, what if you type a message? no response? if no response, that usually means .env is working because it knows the workspace_id, but something in app.js is not grabbing the username/password i think

**Comment by 1234hansel** [comment]
no response and i think I double-triple checked the .env and it was all fine. 
hm...I mean I have to login via a federated id, which shouldn't make any difference, but that's all I can think of.

**Comment by stevenpkg** [comment]
is this still an issue?

**Comment by jpetitfils** [comment]
I've the same problem, when i check the console in my browser i've this error "Failed to load resource: the server responded with a status of 500 (Internal Server Error) :3000/api/message" i can send messages but no response :(

**Comment by jpetitfils** [comment]
problem soveld don't use the username and password from the command "cf service-key my-conversation-service myKey" but those who are in your "Service credential" of your conversation

**Comment by virginiap1** [comment]
I had a similar problem: after npm start I got message that server is running, but there was nothing displayed  for me. Then I've realised I had some empty files in my project, probably there was a problem when I've downloaded the files. I've copied manually the files which were empty and everything is working fine now
