### ISSUE TITLE
csv file does not import in tool

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/conversation-simple#13]
The tutorial for the Watson Conversation service asks to import a csv file  car_intents.csv into the conversation tooling. I can't manage import : is there something wrong with the format ?

**Comment by germanattanasio** [comment]
Make sure you are importing a csv file. I just merged some changes to the README from @sgregglives.

**Comment by doconnor78** [comment]
@PhilippeComte As German said, make sure to check the format of the csv before importing. We've had complaints/issues from folks who have saved the html page `https://github.com/watson-developer-cloud/conversation-simple/blob/master/training/car_intents.csv` as a CSV file.. Users must navigate to this page to save as csv directly: https://raw.githubusercontent.com/watson-developer-cloud/conversation-simple/master/training/car_intents.csv

**Comment by alanbraz** [comment]
Conversation is asking to import CSV only and I can only find a JSON file under master/training!

**Comment by PhilippeComte** [comment]
Hello @alanbraz  , the Conversation tutorial does no longer require a csv file. 
https://www.ibm.com/watson/developercloud/doc/conversation/tutorial_basic.shtml
The Conversation is either filled manually tool or you import a workspace (Import Workspace) which is a json file.

Import a workspace
Select a JSON ﬁle then choose which elements from the workspace to import.
So you should forget about csv file

**Comment by alanbraz** [comment]
I got it! Import a Workspace is a JSON file, so it is correct!

The first time I did it, I created the workspace manually, and tried to import internally, and that one, only accepts CSV!!

Thanks
