### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by akshitabansal97** [watson-developer-cloud/conversation-simple#135]
The project is running like this on local machine. Please help me figure out the problem.The screenshot is provided below.

![image](https://user-images.githubusercontent.com/19350462/28200487-152810cc-688a-11e7-9a9a-ad3ee1e09af3.png)

**Comment by Oliver-I** [comment]
@stevenpkg Can you look into this?

**Comment by stevenpkg** [comment]
Can you please provide more information on how you are building the project and running, any errors etc

**Comment by stevenpkg** [comment]
I suspect that you do not have the conversation service credentials setup correctly

**Comment by salmaadel** [comment]
I have same problem. Watson conversation is not sending any response although credentials are right

**Comment by stevenpkg** [comment]
still need more info, and error logs?

**Comment by akshitabansal97** [comment]
No. Still same problem persists.

**Comment by stevenpkg** [comment]
WORKSPACE_ID=<workspace-id>
CONVERSATION_USERNAME=<conversation-username>
CONVERSATION_PASSWORD=<conversation-password>

**Comment by akshitabansal97** [comment]
@stevenpkg  Sir I have used the imported json carworkspace as workspace id and conversation username and password from the output of cf service-key my-conversation-service myKey. Please verify if I'm using the right credentials.

**Comment by BennyHoang** [comment]
@akshitabansal97 did you remember to rename .env.test to .env? I had same problem, but it worked after i renamed the file

**Comment by germanattanasio** [comment]
@akshitabansal97 I just tried this sample and it's working. Please check your environment.
