### ISSUE TITLE
Slightly NSFW example in the #turn_on intent

### ISSUE THREAD

**Issue by ajborley** [watson-developer-cloud/conversation-simple#136]
One of the examples in the #turn_on intent is: 'play a porn movie'

I expect this was from real world data collected a long time ago :)

**Comment by mitchmason** [comment]
I actually would think this was something recent that was missed. We didnt use much old data in this demo tbh. This just proves that you can't stop people from saying whatever they want, and realistically want to be prepared for at least some of it. In most use cases, you certainly don't want to encourage them to keep going down certain paths, but you do want to prove you understand what they are asking to some capacity.
