### ISSUE TITLE
Application running without watson conversation answering on input user

### ISSUE THREAD

**Issue by salmaadel** [watson-developer-cloud/conversation-simple#137]
this is the link of the app I pushed. Kindly review for help

https://nbdnew.mybluemix.net/

**Comment by salmaadel** [comment]
@stevenpkg  can you check please why watson conversation not working in app

**Comment by miksch27** [comment]
Well, I mixed password and userid. The WCS credentials generates userid and password. The userid has more digits than the password. After that my conversation-sample works well..
