### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by dipakdotyadav** [watson-developer-cloud/conversation-simple#139]
After running the node server the page loads fine but the chat bot doesn't work.
looking in the console i found below headers

```
Request URL:http://localhost:3000/api/message
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:127.0.0.1:3000
```

and response as `{"error":"Resource not found"}`

On console it logs:
```
{ Error: Resource not found
    at Request._callback (/conversation-simple/node_modules/watson-developer-cloud/lib/requestwrapper.js:87:15)
    at Request.self.callback /conversation-simple/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/conversation-simple/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Gunzip.<anonymous> (/conversation-simple/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20) code: undefined, error: 'Resource not found' }
null
```

**Comment by mitchmason** [comment]
resource not found typically means the credentials or workspace_id were invalid. Can you verify you used the correct info? Navigate to the deploy tab in the conversation UI, The circle with an arrow around it on the left tab, and you'll see all the info you need.

**Comment by dipakdotyadav** [comment]
Hi @mitchmason , Thanks , but now i am getting another error `{ error: 'NLU Service Error: Protocol error' }` in file /conversation-simple/node_modules/watson-developer-cloud/lib/requestwrapper.js:88:15

**Comment by BennyHoang** [comment]
@dipakdotyadav are you sure you are using the proper service? NLU looks like the Natural Language Understanding service.

**Comment by germanattanasio** [comment]
@dipakdotyadav this was probably an error in the service, not this sample app. I'm going to close this but let me know if you still see it.

**Comment by santiago-elustondo** [comment]
I am getting a 500 error, started happening today out of nowhere.
<img width="346" alt="screen shot 2018-03-13 at 9 19 10 pm" src="https://user-images.githubusercontent.com/10526720/37378114-3362ed12-2704-11e8-9aa3-a45024c12046.png">

**Comment by mitchmason** [comment]
There was a brief outage around this time, it has been resolved now.
