### ISSUE TITLE
Intent confidence

### ISSUE THREAD

**Issue by agomez314** [watson-developer-cloud/conversation-simple#140]
Hello,
This repo is super awesome. I like to use it as a starting point to develop Watson chatbots so thanks for that. I'd like to know why the intent confidence text is never displayed in my application? The original code from app.js is the following (and it still is for mine):

```
if (response.intents && response.intents[0]) {
    let intent = response.intents[0];
    // Depending on the confidence of the response the app can return different messages.
    // The confidence will vary depending on how well the system is trained. The service will always try to assign
    // a class/intent to the input. If the confidence is low, then it suggests the service is unsure of the
    // user's intent . In these cases it is usually best to return a disambiguation message
    // ('I did not understand your intent, please rephrase your question', etc..)
    if (intent.confidence >= 0.75) {
      responseText = 'I understood your intent was ' + intent.intent;
    } else if (intent.confidence >= 0.5) {
      responseText = 'I think your intent was ' + intent.intent;
    } else {
      responseText = 'I did not understand your intent';
    }
  }
  response.output.text = responseText;
  return response;

```

I have never received a response from Watson with the above text. Why is this? Is the JSON training overriding this text? Is is even necessary? thanks!

**Comment by mitchmason** [comment]
This is actually from a previous version of the app that has since been overwritten. There was a point in time where the service did not have a dialog engine, only intents and entities, so the app was going to simply display the intents returned to the user. We should probably remove this code now, ill work on getting that prioritized. 
now it displays the results from the dialog output instead.

**Comment by agomez314** [comment]
Thank for that. Where can I find a starter template for an app that uses the jobs API and natural language understanding? Thanks!

**Comment by agomez314** [comment]
Thanks for that! also, I'd like to make a cognitive job-hunting app that uses the UBX API and NLA to match jobs according to your resume. Where can I find a starter template for that? Thanks!
