### ISSUE TITLE
Wish: can we get a toolchain/deploy to Bluemix button?

### ISSUE THREAD

**Issue by RogerIBMSnook** [watson-developer-cloud/conversation-simple#142]
Would be handy to have a "deploy to Bluemix" button similar to the very nice Personality Insights demo.

**Comment by germanattanasio** [comment]
This and other sample apps are available here https://console.bluemix.net/developer/watson/starter-kits

**Comment by stevenpkg** [comment]
Do you mean like the the deploy to blue mix in the car dashboard?

https://github.com/watson-developer-cloud/car-dashboard

**Comment by stevenpkg** [comment]
@RogerIBMSnook thank you for your suggestion, I will add this to the wish list
