### ISSUE TITLE
Entities and Dialog

### ISSUE THREAD

**Issue by anthonyherveHCS** [watson-developer-cloud/conversation-simple#15]
Hello, 

I suppose you created Entities and a Dialog in your own Conversation Workspace to get not only the intents but realistic responses.
Did you document this part somewhere ?

Thank you in advance

**Comment by mitchmason** [comment]
Hello, initially conversation only had the intent identification capability, and the responses are simply hardcoded in the application, "i see your intent as xyz", now that entities and dialogs are available within the service we will be adding them to the app as well as the basic instructions how to do so.

**Comment by anthonyherveHCS** [comment]
Thank you. 
In this sample (http://conversation-simple-node-app-doc.mybluemix.net/) do you already use entities and dialog or the responses ("Ok. Turning on the light." or "Sure thing! Do you have a particular genre in mind? Jazz is my personal favorite..") are also hardcoded ?

**Comment by mitchmason** [comment]
Sorry, you win. This was updated to use entities and dialog very recently as the features were released in the service. We will make sure to document this shortly, as well as add the training data to the training folder.

**Comment by anthonyherveHCS** [comment]
Thank you Mitchell.
