### ISSUE TITLE
"AND" & "OR" in conversation workspace  not work

### ISSUE THREAD

**Issue by ysfAskri** [watson-developer-cloud/conversation-simple#22]
when i use in codition :
**"@GENRE:Action AND  #SearchMovies"** or **"@GENRE:Action OR #SearchMovies"**
 not the conversation not return to me _"Action"_ response 
[screenShot of using "AND" ](https://postimg.org/image/4u5glqos7/)
but when i use only one proposition in the condition: 
**"@GENRE:Action"** or  **"#SearchMovies"**
it worked 
[ScreenShot of using only "GENRE:Action"](https://postimg.org/image/45wm2sq2f/)
[ScreenShot of using only "#SearchMovies"](https://postimg.org/image/4wpc8ksfr/)

**Comment by mitchmason** [comment]
I believe this is a bug in the experimental service. We will be releasing the GA service shortly, so please add that on bluemix as its now in the main catalog, and try it there.

**Comment by mitchmason** [comment]
We have now released the GA service. Go to the catalog and now you will see it in the Watson section, NOT the experimental labs section. this version should work for you.
