### ISSUE TITLE
missing render of search skill

### ISSUE THREAD

**Issue by foward** [watson-developer-cloud/conversation-simple#260]
The UI doesnt have the proper render when is a search skill

![image](https://user-images.githubusercontent.com/249026/87351935-86f2a980-c55a-11ea-8b78-6bd676a4f0e1.png)

**Comment by mitchmason** [comment]
There are multiple levels of the sample application that increase in both power and complexity. This app is purposely kept simple so it is easy to understand the code without too much complexity. 
https://github.com/watson-developer-cloud/assistant-intermediate
