### ISSUE TITLE
Simple conversation deployed  but "Watson does not understand" 

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/conversation-simple#38]
Hello , 
I have followed the deployment steps of the simple conversation app on Bluemix. 
I notice : 
-that the Service has to be created manually (only the app is deployed)
-after importing the car_workspace.json file, I get a workspace id and can add the user defined variable.
I get the introduction to the dialog : Hi. It looks like a nice drive today. What would you like me to do?
However , the system does not recognize any sentence at all (keeps answering : I'm not sure about that. You can say things like "Turn on my lights" or "Play some music.")
Is there something I am missing  ? 
Thanks for your help

**Comment by doconnor78** [comment]
@PhilippeComte The workspace takes about 5 to 10 minutes to train the first time it is imported.. Can you let us know if you are still seeing the issue - sorry for the delayed response
