### ISSUE TITLE
Locally conversation-simple

### ISSUE THREAD

**Issue by hayslan1** [watson-developer-cloud/conversation-simple#48]
Hi.
Can someone said where and how to set .env file as describe on the manual. Can someone give a example please?

**Comment by germanattanasio** [comment]
just rename the [`env.example`](https://github.com/watson-developer-cloud/conversation-simple/blob/master/.env.example) file and update the variables there.

**Comment by hayslan1** [comment]
Hi German. Give a example please because only rename and insert the due variables doesn't work for me. Thanks.


Sent from my Samsung device

-------- Original message --------

**Comment by hayslan1** [comment]
Ok German. Solved already. Thanks.


Sent from my Samsung device

-------- Original message --------

**Comment by chughts** [comment]
@hayslan1 this is not the correct forum for questions like this. This is a forum for developers of the SDK who are seeing coding problems with the SDK itself, and either flagging it, or better still providing a fix for a problem they have found. 

For simple questions like yours please use either stackoverflow or developerworks. There your questions will get wider visibility, and if we think that you have found a bug in the SDK we will direct your issue back to this GitHub repro, but the repro should not be the first place you raise your questions.

**Comment by hayslan1** [comment]
@chughts Thanks Soheel.
