### ISSUE TITLE
New Image is not showing

### ISSUE THREAD

**Issue by adolfoalamo** [watson-developer-cloud/conversation-simple#50]
Hi,
I deployed your sample on bluemix and now I and trying to change the graphics. I changed the car dashboard image for a airplane dashboard image using the same name.  I built and deployed the app and the image changes does not appear it still show the car dashboard.  Please advice

**Comment by germanattanasio** [comment]
@adolfoalamo It's hard to see what problem you have based on your description. Open the Web Inspector in Chrome and look at the image that the HTML is using. That's the image you need to change.

I'm closing this since it's not a problem in the code.

**Comment by adolfoalamo** [comment]
I just change the image color and imported using the same name and overwrite the file build deploy and the image is the old image...

**Comment by adolfoalamo** [comment]
@germanattanasio how can I change the images? I am trying to use the same name to not broke the code but I and changing the image with Photoshop.
