### ISSUE TITLE
Confidence

### ISSUE THREAD

**Issue by yogeshkakde** [watson-developer-cloud/conversation-simple#51]
In `app.js` `updateMessage` method, I noticed that confidence is not checked properly.

```
if ( !response.output ) {
    response.output = {};
  } else {
    if ( logs ) {
      // If the logs db is set, then we want to record all input and responses
      id = uuid.v4();
      logs.insert( {'_id': id, 'request': input, 'response': response, 'time': new Date()});
    }

    return response;
  }
  if ( response.intents && response.intents[0] ) {
    var intent = response.intents[0];
    // Depending on the confidence of the response the app can return different messages.
    // The confidence will vary depending on how well the system is trained. The service will always try to assign
    // a class/intent to the input. If the confidence is low, then it suggests the service is unsure of the
    // user's intent . In these cases, it is usually best to return a disambiguation message
    // ('I did not understand your intent, please rephrase your question,' etc..)
    if ( intent.confidence >= 0.75 ) {
      responseText = 'I understood your intent was ' + intent.intent;
    } else if ( intent.confidence >= 0.5 ) {
      responseText = 'I think your intent was ' + intent.intent;
    } else {
      responseText = 'I did not understand your intent';
    }
  }
```

If there is an output in the response confidence is not checked. I noticed that even if I give random sentence, I am getting some random output.

**Comment by Ashwin-93** [comment]
Hi ,
I'm new to this concept can i know how the confidence is measured? confidence = doc.response.intents[0].confidence; ie is it matching with values if exact match "1" like that right
And "node_5_1469049934217" how this is created(ie the number attached with "node" is it random) and linked to other nodes i am bit confused
and can u suggest how to build a small watson application

**Comment by mitchmason** [comment]
@yogeshkakde to answer your original question: 
The code you are seeing is not actually used in the application, you are correct. When we first created this app, there was no dialog piece to the service. So based on the confidence, we would give a response simply parroting back the intent. Now that there is Dialog, this code is no longer used. We did leave it in as an example of what you could do if you did not want to use the Dialog piece of the service.

**Comment by Ashwin-93** [comment]
Thanks  mitchmason

**Comment by dgterry** [comment]
closing as this appears to have been answered.
