### ISSUE TITLE
Binding the "conversation-simple" app to CloudantDB causes app to crash

### ISSUE THREAD

**Issue by JamieGilbertIBM** [watson-developer-cloud/conversation-simple#58]
1. Deploy the Watson conversation sample application using https://bluemix.net/deploy?repository=https://github.com/watson-developer-cloud/conversation-simple 
2. Once deployed, add/bind a Cloudant service to this deployed app. 
3. Restaged the app. App will not come up. It crashes.

activity log shows 'an instance of app is crashed, failed to accept connections with health check timeout'.

**Comment by germanattanasio** [comment]
Hi @JamieGilbertIBM, I'm looking at the manifest and Cloudant is not a requirement for this app. You should be able to run the deploy to Bluemix and have the app working once you update the `WORKSPACE_ID`
