### ISSUE TITLE
Master branch is not working on deploying it to bluemix

### ISSUE THREAD

**Issue by tkhan3** [watson-developer-cloud/conversation-simple#59]
I am working with IBM India and tried to pull the code to build a conversational application. I checked out code from master branch and fowed all the instructions to modify .env file and manifest.yml while.  App is built locally and running perfectly fine.

But when I deployed same app to Bluemix, App is deployed properly. Though front end is appearing but dialogue services are not working. Please note code was checked out from master.

Then I checked out code from previous branch "update-readme-rrberry" and modified it's .env and manifest on deploying this code to Bluemix it's working properly.

On inspecting the code the following changes in SDK are causing problem and not allowing app to integrate with conversation services:

https://github.com/watson-developer-cloud/conversation-simple/commit/f2447db4a274fe5cb26ac8cff5afa800b8109c57

Then I took the code from master branch and reverted changes for this commit and re-deployed the app to Bluemix. App is working properly and running on bluemix.

There is some issue with SDK changes. Please review.

**Comment by aarora91** [comment]
Hi @tkhan3,

I followed the instructions on the readme with the latest code from master branch and it works for me. I am seeing a response from Conversation both-via localhost and when i deploy to Bluemix.

Can you check out your app logs on Bluemix and post them here? That should help us debug the issue. You can access logs by clicking on your app in the dashboard:
![image](https://cloud.githubusercontent.com/assets/5727607/19735677/9624eaa2-9b7a-11e6-9fe1-cf4271709a22.png)

Thanks!

**Comment by germanattanasio** [comment]
I think the problem was that we were not pushing the `.env` file so the credentials were never in the Bluemix app. It should be fixed now
