### ISSUE TITLE
Increment version_date

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/conversation-simple#61]
It would be helpful to increment the [`version_date`](https://github.com/watson-developer-cloud/conversation-simple/blob/c8e7ab1258803c83f52f6fe9e92ea138e357f69f/app.js#L54).

I was using this application to reference the JSON output, but the changes to `dialog_stack` are not reflected because the `version_date` is set to `2016-09-20`.

**Comment by germanattanasio** [comment]
09-20-2016 is the last official `version_date`. There are not new changes AFAIK

**Comment by glennrfisher** [comment]
The [release notes](https://www.ibm.com/watson/developercloud/doc/conversation/releasenotes.shtml) refer to an October 21 release.

It's interesting to note that the dialog stack changes were in the September 20 release, but not reflected in this demo. So I think there's an off-by-one error, where the date would need to be 2016-09-21 or later to see those changes.

**Comment by SirSpidey** [comment]
@glennrfisher: The release notes document a feature release, but not a minor version release. The last minor version that I'm aware of is `2016-09-20`, and that's reflected in the rel notes (and API explorer, and API reference too). 

Are you saying that this date doesn't return the correct info?

**Comment by dgterry** [comment]
@glennrfisher out of curiosity were you experimenting with a local installation of the app or the one hosted at http://conversation-simple.mybluemix.net/ ? I'm wondering if there is potentially a discrepancy between code in the repo and the code running the hosted app.  I plan to update the app with the latest code early next week.

**Comment by glennrfisher** [comment]
@SirSpidey: If there was a feature release on `2016-10-21`, is there any reason not to update the demo to support the new version? Or perhaps there's already an issue for it in a different repository?

@SirSpidey: It's strange, but I don't think we're seeing the results that we expect. According to the `2016-09-20` version, the "`dialog_stack` changes from an array of strings to an array of JSON objects." But the [conversation-simple demo](http://conversation-simple.mybluemix.net/) still returns an array of strings instead of an array of JSON objects.

![conversation](https://cloud.githubusercontent.com/assets/1957636/20069234/64d46dd6-a4e1-11e6-956b-3816730286ee.jpg)

@dgterry Ah, good thinking. I've only tried running the hosted demo at http://conversation-simple.mybluemix.net/. I haven't tried running locally. Maybe the code here hasn't been pushed to the hosted demo? If it's using a `version-date` older than `2016-09-20` than that explains the results I've been seeing.

**Comment by SirSpidey** [comment]
@glennrfisher Hi Glenn, no reason not to update the demo, but I was commenting only on the minor version date that we see in the explorer, reference and release notes. According to my info, Dan O'Connor is responsible for the demo.

**Comment by dgterry** [comment]
Closing based on https://github.com/watson-developer-cloud/conversation-simple/pull/64
