### ISSUE TITLE
remove Watson understands

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-simple#68]
Hi,
I want to know how remove the window Watson understands

Thanks.

**Comment by ashleylord8** [comment]
Hi @sayurimizuguchi,

You can simply go into the file, **app.cs**, and add `display: none;` under `#payload-column` and change the display settings from `display: inline-block;` to `display: none;` under `#view-change-button`. This will get rid of the "Watson understands" window.

**Comment by dgterry** [comment]
closing as Ashley's comment appears to answer the question
