### ISSUE TITLE
Error .env.example

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-simple#75]
Hi,
I try get the info of my IBM bluemix, but dont work (locally).
In the ibm bluemix I have to add the WORKSPACE_ID to work in "Environment Variables".
What am I doing wrong?
Obs.: In the Conversation-enhanced I get the info and work, But in this one I must be doing something wrong, can it help?

Print:
![capturar](https://cloud.githubusercontent.com/assets/23122214/20834192/2046c076-b87b-11e6-8479-7ed7e090aaba.JPG)

Print 2:
![2](https://cloud.githubusercontent.com/assets/23122214/20834227/548cc09c-b87b-11e6-97de-0e8244d7f6da.JPG)

**Comment by germanattanasio** [comment]
Is your code up to date with the code in this repository?

If you look at this [line](https://github.com/watson-developer-cloud/conversation-simple/blob/master/app.js#L42), we are loading the `WORKSPACE_ID` so it should work

**Comment by sayurimizuguchi** [comment]
Exactly, and I try use other Conversation.. dont the car_workspace.

I paste the workspace_id at this line app.js#42 but dont work,

**Comment by germanattanasio** [comment]
try to use the `.env` file and make sure the are no spaces between `=` and the end of the line.

You can also run the app with: `NODE_DEBUG=request npm start`

So that you can see the HTTP requests

**Comment by sayurimizuguchi** [comment]
I check and dont have spaces  between =..
See: 
![capturar jpg2](https://cloud.githubusercontent.com/assets/23122214/20843814/0f058d28-b8a4-11e6-8541-fb8e0d51f8ef.JPG)

Dont work.
I run the app with node debug request npm start and: 
![capturar](https://cloud.githubusercontent.com/assets/23122214/20843779/e5c943be-b8a3-11e6-8c7a-8f4c5f73c10b.JPG)


:(

**Comment by sayurimizuguchi** [comment]
I looked at the node_modules folder and the "request" folder is there with the node files, but it has this error ...

**Comment by germanattanasio** [comment]
`NODE_DEBUG=request npm start`

**Comment by germanattanasio** [comment]
You are running `node debug request npm start`

**Comment by sayurimizuguchi** [comment]
'NODE_DEBUG' is not recognized as an internal command or external, an operable program or a batch file."

**Comment by sayurimizuguchi** [comment]
Hi, I try get the info inline code app.js and work, thanks very much.

**Comment by harshalwavre7** [comment]
@sayurimizuguchi can u please help how did u fix this issue

**Comment by germanattanasio** [comment]
`npm start`

**Comment by harshalwavre7** [comment]
@sayurimizuguchi how did u fix this issue
![issue](https://cloud.githubusercontent.com/assets/26541367/25705788/2357c4aa-30fc-11e7-8453-ffb3c9b2a50e.png)

**Comment by harshalwavre7** [comment]
I am using npm start only and also the .env file has WORKSPACE_ID in it

**Comment by germanattanasio** [comment]
You can always specify the `WORKSPACE_ID` in `app.js`

**Comment by harshalwavre7** [comment]
I am getting a blank page after specifying the WORKSPACE_ID in app.js
