### ISSUE TITLE
Example: Watson Responds.

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-simple#77]
I know if I want send any to Watson in conversation I use the:

```
var latestResponse = Api.getResponsePayload();
var context = latestResponse.context;
Api.sendRequest("Hi Watson!", context);
```
I want to know how do I get Watson to **send something in the conversation**. I saw some examples and tried and it did not work. Can someone help?

I dont now If I'm doing right, but My example is:
```
// var responseText = null;
   //responseText = {};
 var latestResponse = Api.setResponsePayload(); // I dont know if this is true
  var context = latestResponse.context;
  Api.sendRequest('Hi Sayuri!', context); // I try this
  responseText = 'Hi Sayuri!' , context; // I try this too
```

**Comment by jefftmahoney** [comment]
Hi there - I think the reason your example is not working is because `setResponsePayload()` does *not* return any value, and so *nothing* gets assigned to the variable `latestResponse`.

Have you tried doing something like this:
```
Api.setResponsePayload("something I want to send");  // do your value setting
var context = Api.getResponsePayload(); // THEN you can do a 'get' operation
Api.sendRequest("Hi Sayuri!", context); // and send the request
```

**Comment by sayurimizuguchi** [comment]
Hi! 
I try it but dont work :( 
Error: ` Unexpected token O in JSON at position 0(…)`

**Comment by jefftmahoney** [comment]
When is the error occurring?  On the `setResponsePayload()` call, or one of the others?

**Comment by sayurimizuguchi** [comment]
Occurring here: `Api.sendRequest("Hi Sayuri!", context);`

**Comment by ashleylord8** [comment]
Hi @sayurimizuguchi,

I believe I found the solution. You want to do something like this:
```
var latestResponse = Api.getResponsePayload();
var context = latestResponse.context;
Api.setResponsePayload('{"output": {"text": ["Hi Sayuri!"]},"context" : ' + JSON.stringify(context) +'}');
```

The reason why you were getting the `Error: Unexpected token O in JSON at position 0(…)` was since the parameter being passed to `Api.setResponsePayload` wasn't in the correct format. To set the text for the response payload, the correct parameter format would be as follows:
```
'{"output": {"text": ["Desired text goes here."]},"context" : ' + JSON.stringify(context) +'}'
```

I hope this helps!

**Comment by sayurimizuguchi** [comment]
Thank you very much! 
You already helped me a lot here, thank you!

**Comment by ashleylord8** [comment]
Closing since the question to set Watson's response appears to be answered.

**Comment by sayurimizuguchi** [comment]
If i want add one variable with the message, what I do?

var test = 2222;

```
var latestResponse = Api.getResponsePayload();
var context = latestResponse.context;
Api.setResponsePayload('{"output": {"text": ["Hi Sayuri!"]},"context" : ' + JSON.stringify(test) +'}');
```

**Comment by ashleylord8** [comment]
@sayurimizuguchi

I'm not exactly sure what you're asking. You would like to send a variable within the output that is not a string? Or you would like to set it as the context? Or is it something else?

**Comment by sayurimizuguchi** [comment]
I want send a message with some value, and the value save in one variable. 
Can be in context or text, whatever. But when I try to do this it gives me a String error (json)

**Comment by ashleylord8** [comment]
@sayurimizuguchi 

I made a new field within the JSON parameter called `test` and put that within `output`. Also, your variable `test` had to be in string form in order to be a part of the string we're sending as a parameter. So instead of `var test = 2222;` have it be `var test = "2222";`.

```
var latestResponse = Api.getResponsePayload();
var context = latestResponse.context;
var test = "2222";
Api.setResponsePayload('{"output": {"text": ["Hi Sayuri!"], "test": ' + test + '"},"context" : ' + JSON.stringify(context) +'}');
```

Does this help?

**Comment by jefftmahoney** [comment]
@ashleylord8  Cool - so you can facets as needed to the output.  Neat!  
@sayurimizuguchi you can also do `test.toString()` if the variable starts out as a numeric entity.

**Comment by sayurimizuguchi** [comment]
The text is array so it's just going to message inside [] even when I put toString ()

**Comment by ashleylord8** [comment]
@sayurimizuguchi 

Try this:
```
var latestResponse = Api.getResponsePayload();
var context = latestResponse.context;
var test = 2222;
Api.setResponsePayload('{"output": {"text": ["Hi Sayuri!"], "test": ' + test + '},"context" : ' + JSON.stringify(context) +'}');
```
This allows you to add a variable that's not a string within the JSON parameter. I made a new field `test` within the `output` field.

Does this help?

**Comment by sayurimizuguchi** [comment]
Hi Ashley! Thanks very much for help me again, I try your code but dont show the number :(

**Comment by ashleylord8** [comment]
Ah, so I can see that it's there by printing the payload to the console. As you can see here:
```
{"output": {"text": ["Hi Sayuri!"], "test": 2222},"context" : {"conversation_id":.....
```
I didn't realize you wanted the number shown. In that case, you would want to do this:
```
var latestResponse = Api.getResponsePayload();
var context = latestResponse.context;
var test = 2222;
Api.setResponsePayload('{"output": {"text": ["Hi Sayuri!",'+ test + ']},"context" : ' + JSON.stringify(context) +'}');
```

Again, the variable can be a string or the number 2222 in this case.

**Comment by sayurimizuguchi** [comment]
Hi Ashley, this work!!!!! Thanks again!
