### ISSUE TITLE
More function's inside app.js

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-simple#80]
Hello! I would like to add functions in the app.js file so that if someone tries to view the codes, they can not. But these functions will be used, for example:

```
var outputTeste = 2
var latestResponse = Api.getResponsePayload();
console.log(latestResponse);
var context = latestResponse.context;
`Api.setResponsePayload('{"output": {"text": ["Hi Sayuri: ",'+ outputTest + ']},"context" : ' + JSON.stringify(context) +'}');`
```

I try input my code inside app.js but show me error **(Api is not defined)**.
In the case, What I do for insert function's inside one JS file, but, no one can see? 
Can be in another js file, no problem.

Obs.: Before I put these functions inside Index.html, but it's not the best practice on security issues, right?

**Comment by germanattanasio** [comment]
@sayurimizuguchi I think you want to modify the client-side of this sample so you should work with the files in the public folder. The confusion is that the back-end (server side) is in JavaScript but it's not connected to the client-side.

**Comment by sayurimizuguchi** [comment]
I understand, but in case I want to use webservice, both in node and Javascript, and ensure that my code can not be seen, but it will be working with Watson, what can I do?

**Comment by germanattanasio** [comment]
not unless you browserify your files.

**Comment by sayurimizuguchi** [comment]
Thank you for the help!
