### ISSUE TITLE
how to do something in a part of conversation

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-simple#83]
How to perform some function but, if only get a part of the conversation with X intent and X entity?
I had one example with intent and entity, what I need is: 

Example:
I have one context variable and this get the value.
Watson: Hi, what's your name?
User: Sayuri
Watson: Hi $name! //Sayuri in the case

And, after user said your name, I will execute something

I need one example with "if'. I confused with conversation flows, because I dont know how to do it because the  `"dialog_turn_counter": 2` is a array, right?

```
if (context.name[2] !== 'undefined') {
 // do something
}
```

**Comment by SirSpidey** [comment]
Hello @sayurimizuguchi 

See the documentation, specifically [Developing your application](http://www.ibm.com/watson/developercloud/doc/conversation/develop-app.html) and Building a dialog > [Context variables](http://www.ibm.com/watson/developercloud/doc/conversation/dialog-build.html#context-variables).

Also see [StackOverflow](http://stackoverflow.com/questions/tagged/watson-conversation) and post your question is it's not answered there.
