### ISSUE TITLE
How to update the context?

### ISSUE THREAD

**Issue by inngage** [watson-developer-cloud/conversation-simple#84]
Hi guys, how you doing?

First sorry for my noobie question.
It's possible to update the context object in app.js requesting conversation.message() function? I need update my context with the variable value returned from my backend and use it in Conversation node.

Thanks and best regards,
Vinicius

**Comment by germanattanasio** [comment]
You control all the variables and values in `context`, you should be able to set a variable and send it to conversation

**Comment by viniciusdepaula** [comment]
How we can to do this?
