### ISSUE TITLE
Documentation in conversation.js vs payload.js

### ISSUE THREAD

**Issue by tannerpreiss** [watson-developer-cloud/conversation-simple#90]
```The ConversationPanel module is designed to handle all display and behaviors of the conversation column of the app.```
https://github.com/watson-developer-cloud/conversation-simple/blob/dee3a25d7a47e994c248c4b01129867f9c2fd97d/public/js/conversation.js#L2

```The PayloadPanel module is designed to handle all display and behaviors of the conversation column of the app.```
https://github.com/watson-developer-cloud/conversation-simple/blob/6768bd937157011676591bb515f027a6fc047825/public/js/payload.js#L2

How is it that both "Panels" handle _all_ display and behaviors of the conversation column? 

Please be more descriptive regarding roles and responsibilities of the two Panels.

**Comment by germanattanasio** [comment]
@tannerpreiss Thanks for the feedback, can you help us fix that with a PR ?
