### ISSUE TITLE
Results are different from the Bluemix dashboard tooling test

### ISSUE THREAD

**Issue by l-karlin** [watson-developer-cloud/conversation-simple#95]
The results from the demo that was put together using this repo are  different from the results shown in the Conversation dashboard test for the same workspace.

Results from dashboard test
![dasboard-test-irrelevant](https://cloud.githubusercontent.com/assets/26254722/23665940/e1da959a-0327-11e7-97bb-8ef6be1bc314.png)

Results from demo:
![repo-demo-irrelevant](https://cloud.githubusercontent.com/assets/26254722/23665877/b5efc3c4-0327-11e7-94a7-fea381b397c9.png)

**Comment by mitchmason** [comment]
You are likely using two different API versions. The sample app is likely using an older API version and we are still in the process of updating it, while the tryoutpanel is likely the most up to date. 
If you want the same answers, then youll need to update the API version in the sample app code, if you like the sample app responses, keep the old API version.
