### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by renderit** [watson-developer-cloud/conversation-simple#96]
Great work here! However, it seems maybe the UI and things have changed so I'm not able to follow some of the steps mentioned. Can you please help? 
So: 
```
On the Service Details page, click Launch tool.

Click the Import workspace icon in the Conversation service tool. Specify the location of the workspace JSON file in your local copy of the app project:

<project_root>/training/car_workspace.json

Select Everything (Intents, Entities, and Dialog) and then click Import. The car dashboard workspace is created.
```
I don't see this Import workspace, I'm guessing it's just the `Download json` option., but what is meant by "click Import". I'm trying to embed this app with my own conversation bot in another html page.
Or can I replace the `training/car-wordspace.json` with my json file from my app, which is already running?

**Comment by mitchmason** [comment]
The import workspace is the line with an up arrow in it. That is so you can import some json workspace into your conversation tooling. 

To embed your app in another page youll want to have your conversation workspace connected to this app via the .env credentials, and then likely embed the simple UI as an iframe or something like that.
