### ISSUE TITLE
Error in App.js Code

### ISSUE THREAD

**Issue by happypotomous** [watson-developer-cloud/conversation-simple#98]
In app.js Line 43 should be:   if (!workspace || workspace !== '<workspace-id>') {

Right now its:   if (!workspace || workspace == '<workspace-id>')   Its super easy to miss it

**Comment by germanattanasio** [comment]
* `(!workspace || workspace !== '')` will be true if the workspace is valid and if the workspace is `null`
 * `(!workspace || workspace == '')` will be true if there is a workspace and it's not an empty string
